<?php

namespace Database\Seeders\Kosovo;

use App\Features\Markets\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Buke Integrale',
                'brand' => null,
                'variant' => 'furre lokale',
                'category' => 'bakery',
                'image_key' => 'bread',
                'unit' => 'piece',
                'unit_label' => '500g loaf',
                'brand_hint' => 'Whole wheat loaf',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Qumesht Vita',
                'brand' => 'Vita',
                'variant' => '3.2% yndyre',
                'category' => 'dairy',
                'image_key' => 'milk',
                'unit' => 'liter',
                'unit_label' => '1L carton',
                'brand_hint' => 'UHT full-fat milk',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Qumesht Kosmilk',
                'brand' => 'Kosmilk',
                'variant' => 'i fresket',
                'category' => 'dairy',
                'image_key' => 'milk',
                'unit' => 'liter',
                'unit_label' => '1L carton',
                'brand_hint' => 'Fresh local milk',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Veze Fresh',
                'brand' => 'Fresh',
                'variant' => 'M/L',
                'category' => 'dairy',
                'image_key' => 'eggs',
                'unit' => 'pack',
                'unit_label' => '10 cope',
                'brand_hint' => 'Farm eggs',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Vaj luledielli Vital',
                'brand' => 'Vital',
                'variant' => 'i rafinuar',
                'category' => 'oil',
                'image_key' => 'oil',
                'unit' => 'liter',
                'unit_label' => '1L bottle',
                'brand_hint' => 'Sunflower oil',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Sheqer Kristal',
                'brand' => 'Kristal',
                'variant' => 'i bardhe',
                'category' => 'pantry',
                'image_key' => 'sugar',
                'unit' => 'kg',
                'unit_label' => '1kg bag',
                'brand_hint' => 'Fine sugar',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Miell Mlinpek',
                'brand' => 'Mlinpek',
                'variant' => 'tip 500',
                'category' => 'pantry',
                'image_key' => 'flour',
                'unit' => 'kg',
                'unit_label' => '1kg bag',
                'brand_hint' => 'Wheat flour',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Oriz Basmati Gala',
                'brand' => 'Gala',
                'variant' => 'Basmati',
                'category' => 'grains',
                'image_key' => 'rice',
                'unit' => 'kg',
                'unit_label' => '1kg bag',
                'brand_hint' => 'Long grain rice',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Pule e fresket Dukagjini',
                'brand' => 'Dukagjini',
                'variant' => 'e tere',
                'category' => 'meat',
                'image_key' => null,
                'unit' => 'kg',
                'unit_label' => '1kg fresh cut',
                'brand_hint' => 'Fresh poultry',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Patate Vendore',
                'brand' => null,
                'variant' => 'te verdha',
                'category' => 'produce',
                'image_key' => 'potatoes',
                'unit' => 'kg',
                'unit_label' => '1kg bag',
                'brand_hint' => 'Local potatoes',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Kafe Grand',
                'brand' => 'Grand',
                'variant' => 'mesatare',
                'category' => 'beverages',
                'image_key' => null,
                'unit' => 'pack',
                'unit_label' => '200g pack',
                'brand_hint' => 'Ground coffee',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Kos Vita',
                'brand' => 'Vita',
                'variant' => 'i trashe',
                'category' => 'dairy',
                'image_key' => 'milk',
                'unit' => 'liter',
                'unit_label' => '1L bottle',
                'brand_hint' => 'Plain yogurt',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Djathe Sharri i bardhe',
                'brand' => 'Sharri',
                'variant' => 'i bardhe',
                'category' => 'dairy',
                'image_key' => null,
                'unit' => 'pack',
                'unit_label' => '500g pack',
                'brand_hint' => 'White cheese',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Makarona Divella',
                'brand' => 'Divella',
                'variant' => 'penne',
                'category' => 'grains',
                'image_key' => 'pasta',
                'unit' => 'pack',
                'unit_label' => '500g bag',
                'brand_hint' => 'Durum pasta',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Fasule Tetove',
                'brand' => null,
                'variant' => 'e bardhe',
                'category' => 'pantry',
                'image_key' => null,
                'unit' => 'kg',
                'unit_label' => '1kg bag',
                'brand_hint' => 'Dry beans',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Qepe e Verdhe',
                'brand' => null,
                'variant' => 'vendore',
                'category' => 'produce',
                'image_key' => 'onions',
                'unit' => 'kg',
                'unit_label' => '1kg bag',
                'brand_hint' => 'Yellow onions',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Domate Vendore',
                'brand' => null,
                'variant' => 'serre',
                'category' => 'produce',
                'image_key' => null,
                'unit' => 'kg',
                'unit_label' => '1kg',
                'brand_hint' => 'Tomatoes',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Molle Idared',
                'brand' => null,
                'variant' => 'te kuqe',
                'category' => 'produce',
                'image_key' => null,
                'unit' => 'kg',
                'unit_label' => '1kg',
                'brand_hint' => 'Seasonal apples',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Banane Chiquita',
                'brand' => 'Chiquita',
                'variant' => 'import',
                'category' => 'produce',
                'image_key' => null,
                'unit' => 'kg',
                'unit_label' => '1kg',
                'brand_hint' => 'Bananas',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Kripe Solana',
                'brand' => 'Solana',
                'variant' => 'e jodizuar',
                'category' => 'pantry',
                'image_key' => 'salt',
                'unit' => 'kg',
                'unit_label' => '1kg bag',
                'brand_hint' => 'Iodized salt',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Gjalpe President',
                'brand' => 'President',
                'variant' => 'pa kripe',
                'category' => 'dairy',
                'image_key' => null,
                'unit' => 'pack',
                'unit_label' => '250g pack',
                'brand_hint' => 'Butter',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Uje Rugova',
                'brand' => 'Rugova',
                'variant' => 'pa gaz',
                'category' => 'beverages',
                'image_key' => 'water-rugova',
                'unit' => 'bottle',
                'unit_label' => '1.5L bottle',
                'brand_hint' => 'Still water',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Uje Mokna',
                'brand' => 'Mokna',
                'variant' => 'pa gaz',
                'category' => 'beverages',
                'image_key' => 'water-mokna',
                'unit' => 'bottle',
                'unit_label' => '1.5L bottle',
                'brand_hint' => 'Still water',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Coca-Cola',
                'brand' => 'Coca-Cola',
                'variant' => 'classic',
                'category' => 'beverages',
                'image_key' => 'cola',
                'unit' => 'can',
                'unit_label' => '0.33L can',
                'brand_hint' => 'Carbonated drink',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Pepsi',
                'brand' => 'Pepsi',
                'variant' => 'classic',
                'category' => 'beverages',
                'image_key' => 'pepsi',
                'unit' => 'can',
                'unit_label' => '0.33L can',
                'brand_hint' => 'Carbonated drink',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Fanta Orange',
                'brand' => 'Fanta',
                'variant' => 'orange',
                'category' => 'beverages',
                'image_key' => 'cola',
                'unit' => 'can',
                'unit_label' => '0.33L can',
                'brand_hint' => 'Orange soda',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Leng Portokalli Fructal',
                'brand' => 'Fructal',
                'variant' => '100% portokall',
                'category' => 'beverages',
                'image_key' => null,
                'unit' => 'liter',
                'unit_label' => '1L carton',
                'brand_hint' => 'Orange juice',
                'is_core_basket' => true,
            ],
            [
                'name' => 'Caj i zi Podravka',
                'brand' => 'Podravka',
                'variant' => 'black tea',
                'category' => 'beverages',
                'image_key' => null,
                'unit' => 'pack',
                'unit_label' => '100g pack',
                'brand_hint' => 'Tea',
                'is_core_basket' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::query()->updateOrCreate(
                ['name' => $product['name']],
                [
                    'brand' => $product['brand'],
                    'variant' => $product['variant'],
                    'category' => $product['category'],
                    'image_key' => $product['image_key'],
                    'unit' => $product['unit'],
                    'unit_label' => $product['unit_label'],
                    'brand_hint' => $product['brand_hint'],
                    'is_core_basket' => $product['is_core_basket'],
                ]
            );
        }
    }
}
